version: "2.2"
services:
 webapp:
  build: .
  ports:
   - "3434:8080"
 db:    
   image: mysql:8.2
   restart: always
   ports:
    - "3306:3306"
   environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_ALLOW_EMPTY_PASSWORD=true
    - MYSQL_USER=petclinic
    - MYSQL_PASSWORD=petclinic
    - MYSQL_DATABASE=petclinic
   volumes:
    - my-datavolume:/var/lib/mysql  
 postgres:
  image: postgres:16.1
  ports:
   - "5432:5432"
  environment:
   - POSTGRES_PASSWORD=petclinic
   - POSTGRES_USER=petclinic
   - POSTGRES_DB=petclinic
  volumes:
   - "./new_postgres_data:/var/lib/postgresql/data"
volumes:
 my-datavolume:     
